### ISSUE TITLE
Popup not show all options

### ISSUE THREAD

**Issue by SnowCreative** [Jako/TimerangeTV#2]
The time popups aren't showing the full range of options as set in the settings. Just a couple are showing up. This is happening on multiple websites. Using MODX 2.7.2 and TimerangeTV 1.2.0-pl2. Images attached so problem, and the settings for the TV.

![Screen Shot 2020-01-04 at 12 00 08 PM](https://user-images.githubusercontent.com/2528374/71769122-e9535900-2eea-11ea-88db-2d11f37a184d.png)
![Screen Shot 2020-01-04 at 12 08 59 PM](https://user-images.githubusercontent.com/2528374/71769130-07b95480-2eeb-11ea-882b-442e2006116a.png)

**Comment by jmacdonald-spectacle** [comment]
I'm having the same problem in both a new install and in the latest update.

**Comment by hitodev** [comment]
Hello
Same problem with MODX Revolution 2.8.2-pl, only one option in the dropdown wathever min. and max. values.

**Comment by Jako** [comment]
Fixed with 1.2.1

**Comment by SnowCreative** [comment]
Works great now. Thanks!
